/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ReportModel } from '../models/ReportModel';

export class HTMLRenderer {
  
  public render(report: ReportModel): string {
    const { metadata, institution, project, plagiarism, evidence, ai, certification } = report;
    
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Plagiarism Report - ${project.projectTitle}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    header { text-align: center; border-bottom: 2px solid #0056b3; padding-bottom: 20px; margin-bottom: 30px; }
    .logo { max-width: 150px; }
    h1 { color: #0056b3; margin-bottom: 5px; }
    h2 { color: #444; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f4f4f4; width: 30%; }
    .risk-Critical { color: #dc3545; font-weight: bold; }
    .risk-High { color: #fd7e14; font-weight: bold; }
    .risk-Medium { color: #ffc107; font-weight: bold; }
    .risk-Low { color: #28a745; font-weight: bold; }
    .certification-box { border: 2px solid #28a745; padding: 15px; background: #eafaf1; border-radius: 5px; }
    footer { text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 0.9em; color: #666; }
  </style>
</head>
<body>

  <header>
    ${institution.logo ? `<img src="${institution.logo}" alt="${institution.name} Logo" class="logo">` : ''}
    <h1>${institution.name}</h1>
    <h3>${institution.school} | ${institution.committee}</h3>
    <p><strong>Plagiarism & AI Detection Report</strong></p>
  </header>

  <section id="metadata">
    <table>
      <tr><th>Report ID</th><td>${metadata.id}</td></tr>
      <tr><th>Generated Date</th><td>${new Date(metadata.generatedAt).toLocaleString()}</td></tr>
    </table>
  </section>

  <section id="project-info">
    <h2>Project Information</h2>
    <table>
      <tr><th>Project Title</th><td>${project.projectTitle}</td></tr>
      <tr><th>Department</th><td>${project.department}</td></tr>
      <tr><th>Programme / Level</th><td>${project.programme} - ${project.level}</td></tr>
      <tr><th>Session</th><td>${project.session}</td></tr>
      <tr><th>Supervisor</th><td>${project.supervisor}</td></tr>
    </table>
  </section>

  <section id="student-info">
    <h2>Student Information</h2>
    <table>
      <thead>
        <tr><th>Name</th><th>Matric Number</th></tr>
      </thead>
      <tbody>
        ${project.students.map(s => `<tr><td>${s.fullName}</td><td>${s.matricNumber}</td></tr>`).join('')}
      </tbody>
    </table>
  </section>

  <section id="executive-summary">
    <h2>Executive Summary</h2>
    <table>
      <tr><th>Plagiarism Type</th><td>${plagiarism.plagiarismType}</td></tr>
      <tr><th>Similarity Score</th><td>${(plagiarism.similarityScore * 100).toFixed(1)}%</td></tr>
      <tr><th>Overall Risk</th><td class="risk-${plagiarism.overallRisk}">${plagiarism.overallRisk}</td></tr>
    </table>
  </section>

  <section id="ai-interpretation">
    <h2>AI Interpretation</h2>
    <p><strong>Confidence:</strong> ${(ai.confidence * 100).toFixed(1)}%</p>
    <p><strong>Summary:</strong> ${ai.summary}</p>
    
    <h3>Evidence Explanation</h3>
    <ul>
      ${ai.evidenceExplanation.map(exp => `<li>${exp}</li>`).join('')}
    </ul>

    <h3>Recommendations</h3>
    <ul>
      ${ai.recommendations.map(rec => `<li>${rec}</li>`).join('')}
    </ul>
    
    ${ai.lecturerComments ? `<h3>Lecturer Comments</h3><p>${ai.lecturerComments}</p>` : ''}
    ${ai.studentFeedback ? `<h3>Student Feedback</h3><p>${ai.studentFeedback}</p>` : ''}
  </section>

  <section id="evidence-summary">
    <h2>Evidence Details</h2>
    <table>
      <tr><th>Candidate Paper Title</th><td>${evidence.candidatePaperTitle || 'N/A'}</td></tr>
      <tr><th>Total Words</th><td>${evidence.candidateWordCount}</td></tr>
      <tr><th>Exact Match Count</th><td>${evidence.exactMatchCount}</td></tr>
      <tr><th>Jaccard Similarity</th><td>${(evidence.jaccardSimilarity * 100).toFixed(2)}%</td></tr>
    </table>
  </section>

  <section id="certification">
    <h2>Certification</h2>
    <div class="certification-box">
      <p>This report was generated by the <strong>certified AI Infrastructure</strong>.</p>
      <ul>
        <li><strong>AI Provider:</strong> ${certification.aiProvider} (${certification.model})</li>
        <li><strong>Evidence Version:</strong> ${certification.evidenceVersion}</li>
        <li><strong>Interpretation Version:</strong> ${certification.interpretationVersion}</li>
        <li><strong>Runtime Status:</strong> ${certification.runtimeStatus}</li>
      </ul>
    </div>
  </section>

  <footer>
    <p>Generated by ${institution.shortName} Plagiarism Checker System</p>
    <p>Report ID: ${metadata.id}</p>
  </footer>

</body>
</html>
    `.trim();
  }
}
